services:
  postgres:
    image: postgres:15-alpine
    container_name: fitgenius-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fitgenius
      POSTGRES_USER: simo
      POSTGRES_PASSWORD: schweps123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - fitgenius-network

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fitgenius-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fitgenius.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - fitgenius-network

volumes:
  postgres_data:
    driver: local

networks:
  fitgenius-network:
    driver: bridge